### PR TITLE
Move requirements.txt and test/requirements.txt as source of truth

### PR DESCRIPTION
**Pull request by rogebrd**
## **Checklist**

**General Contributing**
- [x] Have you read the Code of Conduct and signed the [CLA](https://opensource.dropbox.com/cla/)?

**Is This a Code Change?**
- [x] Non-code related change (markdown/git settings etc)
- [ ] SDK Code Change
- [ ] Example/Test Code Change

**Validation**
- [x] Does `tox` pass?
- [x] Do the tests pass?

### CODE REVIEW

**Review by mtruong-dbx — APPROVED** [review]

**Comment by marmarek** [comment]
This resulted in adding `twine` in `install_reqs`, which then pulled in several other dependencies. Is that really necessary at runtime (as opposed from dev env)?

**Comment by greg-db** [comment]
@marmarek Thanks for the note! I'll ask the team to see if this is needed and if we can change that.

**Comment by greg-db** [comment]
@marmarek We've updated `install_reqs` to no longer pull in from requirements.txt.

**Comment by marmarek** [comment]
Thanks!

**Pull request merged**
