### PR TITLE
Updated sphinx syntax

### LINKED ISSUE #227: New line in docs is incorrectly broken in readthedocs
Hi,

the argument `expiration` in [OAuth2FlowNoRedirectResult](https://dropbox-sdk-python.readthedocs.io/en/latest/api/oauth.html#dropbox.oauth.OAuth2FlowNoRedirectResult) is split into two lines in the documentation, which should not happen. I think this is because of the new line in the [code](https://github.com/dropbox/dropbox-sdk-python/blob/7b75667e766572b7df3a75ee03ff6098088c5d61/dropbox/oauth.py#L52) itself.

I'm not sure how readthedocs treats new lines which is why I didn't create a pull request myself.

Screenshot:
Screenshot

Thanks!

### PR DESCRIPTION
**Pull request by Lucurus**
As outlined in #230 the documentation style is not consistent. This fixes the style for the OAuth file.

Fixes #227

### CODE REVIEW

**Comment by Lucurus** [comment]
As described in #230 there are different documentation styles in some files which I tried to unify. 
Since I couldn't find a guide about which one is preferred I just went with the official one but I can also switch it to `:Args:` style if that's preferred.

**Comment by Lucurus** [comment]
Fixes #227

**Comment by rogebrd** [comment]
Looks good to me, would you mind just linking me to the guide you used?

**Comment by Lucurus** [comment]
Thanks! Of course, it's from [Sphinx](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#signatures).

**Review by rogebrd — APPROVED** [review]
Really appreciate you going through and fixing these comments!

**Comment by Lucurus** [comment]
Pleasure! Thanks for approving.

**Comment by Lucurus** [comment]
@rogebrd  Just to confirm, would you like me to add anything else because this would be ready to merge from my side?

**Pull request merged**
