### PR TITLE
Improve experience for contributors

### PR DESCRIPTION
**Pull request by ewjoachim**
Hi,

You left a print statement in an earlier commit, so I wanted to make a pull request for removing it. While doing so, I forked the repo and launched the tests, and it failed because you need to be inside the test folder for it to run correctly, but that's just because the files around are accessed through a direct path, so I propose a small change that gives room for more flexibility.

Finally, 2 of your tests were initially failing after the recent ".reason"/".error" refactoring, so I fixed them.

If you prefer, 3 different pull requests, just tell me.

Would you be ok to using [tox](https://tox.readthedocs.org/en/latest/) instead of calling "python2" and "python3" directly in runtests. For those using virtualenvs instead of globally installing packages, that can smooth this a lot.

### CODE REVIEW

**Comment by braincore** [comment]
Since we have our own build and release process, I've committed your changes outside of the GitHub flow. Thanks a lot!

**Comment by braincore** [comment]
Oh! And I'll make a task to investigate tox.

**Comment by braincore** [comment]
FYI, I've added support for using tox. Thanks for the tip!

**Comment by ewjoachim** [comment]
My pleasure !

**Pull request closed without merging**
